MFIBlog/MFIBlog/urls.py
from django.contrib import admin
from django.urls import path , include 
from articles import views
from django.conf.urls.static import static
from django.conf import settings



urlpatterns = [
    
    path('AdminFurkan/', include('admin_honeypot.urls', namespace='admin_honeypot')),
    path('mfi05boks10network99/', admin.site.urls),
    path('', views.index , name = "index"),
    path('articles/', include("articles.urls")),
    path('ckeditor', include('ckeditor_uploader.urls')),
    
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

MFIBlog/articles/urls.py
from django.contrib import admin
from articles import views
from django.urls import path



app_name = "articles"


urlpatterns = [

    path('network/', views.networkArticles , name = "network"),
    path('SoC/', views.SoCArticles , name = "SoC"),
    path('forensic/', views.forensicArticles , name = "forensic"),
    path('karisik/', views.karisikArticles , name = "karisik"),

    path('networkDetail/<int:id>', views.networkDetail , name = "networkDetail"),
    path('SoCDetail/<int:id>', views.SoCDetail , name = "SoCDetail"),
    path('forensicDetail/<int:id>', views.forensicDetail , name = "forensicDetail"),
    path('karisikDetail/<int:id>', views.karisikDetail , name = "karisikDetail"),  

]

MFIBlog/templates/SoCArticles.html
{% extends "layout.html" %}

{% block Image %}

            <section id = "securityArticlesImage">
                <div class = "container">
                    <div class = "row">
                        {% include  "includes/navbar.html" %}
                    </div>
                </div>
            </section>

{% endblock Image %}



{% block Title %}
            
            <section id = "securityTitle">
                <div class = "coll-lg-12">
                    <h3> GENERAL SECURİTY </h3>
                </div>
            </section>


            
            <section id = "search">
                <div class = "container">
                    <div class = "row">
                            <div class = "coll-12 search">
                                <form>
                                    {% csrf_token %}
                                    <input type="text" class = "keyword" name="keyword" placeholder = "Anahtar Kelimeler" maxlength = 30>
                                    <button type="submit" class = "btn btn-danger more"> Ara</button>
                                </form>
                            </div>
                        
                    </div>
                </div>
            </section>


            
{% endblock Title %}



{% block content %}

            <section id = "securityArticlesList">
                {% if SoCArticles %}
                {% for articlecontext in  SoCArticles %}
                <div class = "container">
                    <div class = "securityArticles-content text-center">
                        <div class = "row">
                            <div class = "col-lg-6 distance article">
                                {% if articlecontext.articleImage %}
                                <div class ="text-center distance">
                                    <img class = "image" style="max-width:100%; margin: 2%;" src = "{{articlecontext.articleImage.url}}" alt = ""/>
                                </div>
                                {% endif %}
                            </div>
                            <div class = "col-lg-6 text-left distance article">
                                <h4> {{articlecontext.title | safe}}</h4> 
                                <p> {{articlecontext.content | safe | truncatechars_html:200}}</p>
                                <a style = "float : right;" href = "{% url 'articles:SoCDetail' articlecontext.id %}" class = "btn btn-danger more"> Devamını Oku</a>
                            </div>

                            <div class = "col-lg-12 distance middle">
                            </div>
                        </div>
                    </div>
                </div>
                {% endfor %}
                {% else %}
                <div class = "alert alert-danger">
                Henüz makale eklenmemiştir
                </div>
                {% endif %}   
            </section>



            <nav aria-label="Page navigation example" style = "background-color: #E0E0E0;">
                <ul class="pagination">
                    {% if SoCArticles.has_previous %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ SoCArticles.previous_page_number }}" aria-label="Previous">
                            <span aria-hidden="true">&laquo;</span>
                            <span class="sr-only">Previous</span>
                        </a>
                    </li>
                    {% endif %}

                    {% if SoCArticles.paginator.num_pages %}
                    <span class="current ">
                       Sayfa {{ SoCArticles.paginator.num_pages  | safe}} / {{ SoCArticles.number  | safe}}
                    </span>
                    {% endif %}
    
                    {% if SoCArticles.has_next %}
                    <li class="page-item">
                        <a class="page-link"  href="?page={{ SoCArticles.next_page_number }}" aria-label="Next">
                            <span aria-hidden="true">&raquo;</span>
                            <span class="sr-only">Next</span>
                        </a>
                    </li>
                    {% endif %}
                </ul>
            </nav>

{% endblock content %}

MFIBlog/templates/detail.html
{% extends "layout.html" %}

{% block Title %}

    <section id = "detailImage" style = "background-image: url('{{detail.articleImage.url}}') ;">
        <div class = "container">
            <div class = "row">
                {% include  "includes/navbar.html" %}
            </div>
        </div>
    </section>




{% endblock Title %}

{% block content %}
<section>
        
    <div class = "col-lg-12 distance middle">
    </div>     

     <div class = "container">
        <div class = " detailContent">
            <div class = "col-lg-12 text-left">
                <h3>{{detail.title}}</h3>
            </div>
            <hr>
            <div class = "row">
                <div class="col-lg-9 ">
                            {% if detail.articleImage %}
                            <img class="img-fluid rounded" src="{{detail.articleImage.url}}" alt="">
                            {% endif %}
                        <p>
                        {{detail.content | safe }}
                        </p>
                </div>

                <div class="col-lg-3 detailSonMakaleler">
                    <h5>NETWORK</h5>
                        <hr>
                        {% for articlecontext in  networkArticles %}
                                <a href = "{% url 'articles:networkDetail' articlecontext.id %}"> {{articlecontext.title | safe}}</a>
                                <br>
                        {% endfor %}
                        <br><br>
                    <h5>SOC</h5>
                        <hr>
                        {% for articlecontext in  SoCArticles %}
                                <a href = "{% url 'articles:SoCDetail' articlecontext.id %}"> {{articlecontext.title | safe}}</a>
                                <br>
                        {% endfor %}
                        <br><br>
                    <h5>FORENSİC</h5>
                        <hr>
                        {% for articlecontext in  forensicArticles %}
                                <a href = "{% url 'articles:forensicDetail' articlecontext.id %}"> {{articlecontext.title | safe}}</a>
                                <br>
                        {% endfor %}
                        <br><br>
                    <h5>MİXED</h5>
                        <hr>
                        {% for articlecontext in  karisikArticles %}
                                <a href = "{% url 'articles:karisikDetail' articlecontext.id %}"> {{articlecontext.title | safe}}</a>
                                <br>
                        {% endfor %}
                        <br><br>
                        
                </div>
            </div>
        </div>
    </div>
</section>




<section>
    <div class = "container">
            <div class = "row">
                <div class = "col-lg-12">
                    
                    {% if detail.articlesVideo %}
                        <video width="640" height="360" controls="controls" src="/media/{{detail.articlesVideo}}" type="video/mp4">
                            Tarayıcınız video etiketini desteklemiyor.
                        </video>
                    {% else %}
                    {% endif %}
                    
                    <hr>
                    <p>{{detail.createDate | safe}} Tarihinde Yayınlandı</p>
                </div>
            </div>
    </div>
</section>



{% endblock content %}

MFIBlog/templates/forensicArticles.html
{% extends "layout.html" %}

{% block Image %}

            <section id = "forensicArticlesImage">
                <div class = "container">
                    <div class = "row">
                        {% include  "includes/navbar.html" %}
                    </div>
                </div>
            </section>

{% endblock Image %}



{% block Title %}
            
            <section id = "forensicTitle">
                <div class = "container">
                    <div class = "row">
                        <div class = "col-12">
                            <h3> FORENSİC </h3>
                        </div>
                    </div> 
                </div>
            </section>


            
            <section id = "search">
                <div class = "container">
                    <div class = "row">
                            <div class = "col-12 search">
                                <form>
                                    {% csrf_token %}
                                    <input type="text" class = "keyword" name="keyword" placeholder = "Anahtar Kelimeler" maxlength = 30>
                                    <button type="submit" class = "btn btn-danger more"> Ara</button>
                                </form>
                            </div>
                        
                    </div>
                </div>
            </section>
                

            
{% endblock Title %}



{% block content %}


            <section id = "forensicArticlesList">
                {% if forensicArticles %}
                {% for articlecontext in  forensicArticles %}
                <div class = "container">
                    <div class = "forensicArticles-content text-center">
                        <div class = "row">
                            <div class = "col-lg-6 distance article">
                                {% if articlecontext.articleImage %}
                                <div class ="text-center distance">
                                    <img class = "image" style="max-width:100%; margin: 2%;" src = "{{articlecontext.articleImage.url}}" alt = ""/>
                                </div>
                                {% endif %}
                            </div>
                            <div class = "col-lg-6 text-left distance article">
                                <h4> {{articlecontext.title | safe}}</h4> 
                                <p> {{articlecontext.content | safe | truncatechars_html:200}}</p>
                                <a style = "float : right;" href = "{% url 'articles:forensicDetail' articlecontext.id %}" class = "btn btn-danger more"> Devamını Oku</a>
                            </div>

                            <div class = "col-lg-12 distance middle">
                            </div>
                        </div>
                    </div>
                </div>
                {% endfor %}
                {% else %}
                <div class = "alert alert-danger">
                Henüz makale eklenmemiştir
                </div>
                {% endif %}   
            </section>


            <nav aria-label="Page navigation example" style = "background-color: #E0E0E0;">
                <ul class="pagination">
                    {% if forensicArticles.has_previous %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ forensicArticles.previous_page_number }}" aria-label="Previous">
                            <span aria-hidden="true">&laquo;</span>
                            <span class="sr-only">Previous</span>
                        </a>
                    </li>
                    
                    {% endif %}

                    {% if forensicArticles.paginator.num_pages %}
                    <span class="current ">
                       Sayfa {{ forensicArticles.paginator.num_pages | safe }} / {{ forensicArticles.number  | safe}}
                    </span>
                    {% endif %}

                    {% if forensicArticles.has_next %}
                    <li class="page-item">
                        <a class="page-link"  href="?page={{ forensicArticles.next_page_number }}" aria-label="Next">
                            <span aria-hidden="true">&raquo;</span>
                            <span class="sr-only">Next</span>
                        </a>
                    </li>
                    {% endif %}
                </ul>
            </nav>

{% endblock content %}

MFIBlog/templates/index.html
<!doctype html>
{% load static %}

    <html lang="en">
        <head>
            <meta charset="utf-8">
            <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
            <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
            <link rel="stylesheet" href="{% static 'css/main1.css' %}">
            <link rel="stylesheet" href="{% static 'css/main2.css' %}">
            <link rel="stylesheet" href="{% static 'css/index.css' %}">
            <link href="https://fonts.googleapis.com/css2?family=Architects+Daughter&display=swap" rel="stylesheet">           
            <link href="https://fonts.googleapis.com/css2?family=Saira:wght@300&display=swap" rel="stylesheet">
            <link href="https://fonts.googleapis.com/css2?family=Exo&family=Istok+Web&display=swap" rel="stylesheet">        
        </head>
  
        <body>



            <section id = "index">
                <div class = "container">
                    <div class = "row">
                        {% include  "includes/navbar.html" %}
                    </div>
                </div>
            
                <div class ="row text-center">
                    <div class = "col-lg-12">
                        <h1>Web Siteme Hoşgeldiniz</h1>
                    </div>
                    
                    <div class = "col-lg-12">
                        <h2>Yazılarıma Gözatın</h2>
                    </div>
                    
                    <div class = "col-lg-12">
                        <a href = "/#network"><button type = "button" class = "btn btn-primary btn-lg">Gezinmeye Başla</button></a>
                    </div>
                </div>
            </section>



            <section id = "network">
                <div class = "container">
                    <div class = "network-top text-center">
                        <h3> NETWORK </h3>
                        <p>NETWORK ARTICLES</p>
                    </div>

                    <div class = "network-content text-center">
                        <div class = "row">
                            {% if networkArticles %}
                            {% for articlecontext in   networkArticles %}
                            <div class = "col-lg-4 distance">
                                <div class = "linkModified">
                                    <a href = "{% url 'articles:networkDetail' articlecontext.id %}" >
                                        {% if articlecontext.articleImage %}
                                        <div>
                                            <img class = "image img-thumbnail" style="max-width:100%" src = "{{articlecontext.articleImage.url}}" alt = ""/>
                                        </div>
                                        {% endif %}
                                        <h4>{{articlecontext.title | safe}}</h4>
                                        <p>{{articlecontext.summary | safe }}</p>
                                    </a>
                                </div>
                            </div> 
                            {% endfor %}
                            {% else %}
                            <div class = "alert alert-danger">
                            Henüz makale eklenmemiştir
                            </div>
                            {% endif %}                        </div>
                    </div>
                    <div class = "text-center">
                        <a href = " {% url 'articles:network' %}" class = "btn btn-danger more"> Daha Fazla </a>
                    </div>
                </div>  
            </section>



            <section id = "security">
                <div class = "container">
                    <div class = "security-top text-center">
                        <h3> GENERAL SECURİTY </h3>
                        <p>GENERAL SECURİTY ARTICLES</p>
                    </div>
                    <div class = "security-content text-center">
                        <div class = "row">
                            {% if SoCArticles %}
                            {% for articlecontext in   SoCArticles %}
                            <div class = "col-lg-4 distance">
                                <div class = "linkModified">
                                    <a href = "{% url 'articles:SoCDetail' articlecontext.id %}" >
                                        <div class = "card">
                                            {% if articlecontext.articleImage %}
                                            <img class = "image img-thumbnail" style="max-width:100%" src = "{{articlecontext.articleImage.url}}" alt = ""/>
                                            {% endif %}
                                            <div class = "card-block">
                                                <h4 class = "card-title">{{articlecontext.title | safe}}</h4>
                                                <p class = "card-subtitle text-muted">{{articlecontext.summary | safe }}</p>
                                            </div>
                                        </div>
                                    </a>
                                </div>
                            </div>
                            {% endfor %} 
                            {% else %}
                            <div class = "alert alert-danger">
                            Henüz makale eklenmemiştir
                            </div>
                            {% endif %}
                        </div>
                    </div>
                    <div class = "text-center">
                        <a href = " {% url 'articles:SoC' %}" class = "btn btn-danger more"> Daha Fazla </a>
                    </div>
                </div>
            </section>



            <section id = "forensic">
                <div class = "container">
                    <div class = "forensic-top text-center">
                        <h3> FORENSIC </h3>
                        <p>FORENSIC ARTICLES</p>
                    </div>
                    <div class = "forensic-content text-center">
                        <div class = "row">
                            {% if forensicArticles %}
                            {% for articlecontext in   forensicArticles %}
                            <div class = "col-lg-4 distance">                                
                                <div class = "linkModified">
                                    <a href = "{% url 'articles:forensicDetail' articlecontext.id %}"  >
                                        {% if articlecontext.articleImage %}
                                        <div>
                                            <img class = "image img-thumbnail" src = "{{articlecontext.articleImage.url}}" alt = ""/>
                                        </div>
                                        {% endif %}
                                        <h4>{{articlecontext.title | safe}}</h4>
                                        <p>{{articlecontext.summary | safe }}</p>
                                    </a>
                                </div>
                            </div>
                            {% endfor %}                             
                            {% else %}
                            <div class = "alert alert-danger">
                            Henüz makale eklenmemiştir
                            </div>
                            {% endif %}
                        </div>
                    </div>
                    <div class = "text-center">
                        <a href = " {% url 'articles:forensic' %}" class = "btn btn-danger more"> Daha Fazla </a>
                    </div>
                </div>
            </section>




             <section id = "translate">
                <div class = "container">
                    <div class = "translate-top text-center">
                        <h3> MIXED </h3>
                        <p>MIXED ARTICLES</p>
                    </div>
                    <div class = "translate-content text-center">
                        <div class = "row">
                            {% if karisikArticles %}
                           {% for articlecontext in   karisikArticles %}
                            <div class = "col-lg-4 distance">
                                <div class = "linkModified">
                                    <a href ="{% url 'articles:karisikDetail' articlecontext.id %}"  >
                                        <div class = "card">
                                            {% if articlecontext.articleImage %}
                                            <img class = "image img-thumbnail" style="max-width:100%" src = "{{articlecontext.articleImage.url}}" alt = ""/>
                                            {% endif %}
                                            <div class = "card-block">
                                                <h4 class = "card-title">{{articlecontext.title | safe}}</h4>
                                                <p class = "card-subtitle text-muted">{{articlecontext.summary | safe }}</p>
                                            </div>
                                        </div>
                                    </a>
                                </div>
                            </div>
                            {% endfor %}                           
                            {% else %}
                            <div class = "alert alert-danger">
                            Henüz makale eklenmemiştir
                            </div>
                            {% endif %}
                        </div>
                    </div>
                    <div class = "text-center">
                        <a href = " {% url 'articles:karisik' %}" class = "btn btn-danger more"> Daha Fazla </a>
                    </div>
                </div>
            </section>

        
        
 
            <section id = "about">
                <div class = "container">
                    <div class = "about-top text-center">
                        <h3>ABOUT</h3>
                        <p>MUHAMMED FURKAN İLKEL</p>
                    </div>
                    <div class = "about-content">
                        <div class = "row">
                            <div class = "col-lg-4 text-center">
                                <div class = "about-circle">
                                    <img style="width: 208px;  height: 208px; border-radius: 208px;" src = "" alt = ""/>
                                </div>
                                    <h4>Muhammed Furkan Ilkel</h4>
                                    <h5>Blogger</h5>
                                </div>
                                <div class = "col-lg-8">
                                    <p>
                                        Fırat Üniversitesi bilgisayar mühendisiği 4. sınıf öğrencisiyim.Ağ ve güvenlik alanlarına ilgi duyuyor ve kariyerime bu alanlarda yön vermek istiyorum. 
                                        Kendi kodlamış olduğum web sitemi, ilgi duyduğum alanlarda araştırmalar yaparken öğrendiklerimi yazılara dökerek benimle aynı ilgi alanına sahip insanlarla paylaşabilmek için oluşturdum. 
                                        Önerileriniz veya araştırmamı istediğiniz konular olursa bana mail yoluyla ulaşabilirsiniz. Keyifli okumalar.
                                    </p>
                                </div>
                            </div>
                        </div>
                    </div>
                </section>

            

                <section id = "footer">
                    <div class = "container">
                        <div class = "row"> 
                            <div class = "col-lg-6">
                                <p>| Copyright © 2020-2021 MFIBlog.com |</p>
                            </div>
                            <div class = "col-md-6">
                                <a href = ""><img src = "/media/icons/linkedin.png"  width="45" height="45" /></a>
                                <a href = ""><img src = "/media/icons/github.png"  width="50" height="50" /></a>
                                <a href = ""><img src = "/media/icons/facebook.png" width="50" height="50" /></a>
                            </div>
                        </div>
                    </div>
                </section>



            <script src = "{% static 'js/jquery-3.1.1.min.js' %}"></script>
            <script src = "{% static 'js/bootstrap.min.js' %}"></script>
            <script src = "{% static 'js/main-index.js' %}"></script>

        </body>
    </html>

MFIBlog/templates/karisikArticles.html
{% extends "layout.html" %}

{% block Image %}

            <section id = "translateArticlesImage">
                <div class = "container">
                    <div class = "row">
                        {% include  "includes/navbar.html" %}
                    </div>
                </div>
            </section>

{% endblock Image %}



{% block Title %}
            
            <section id = "translateTitle">
                <div class = "col-lg-12">
                    <h3> Karışık </h3>
                </div>
            </section>


            
            <section id = "search">
                <div class = "container">
                    <div class = "row">
                            <div class = "col-12 search">
                                <form>
                                    {% csrf_token %}
                                    <input type="text" class = "keyword" name="keyword" placeholder = "Anahtar Kelimeler" maxlength = 30>
                                    <button type="submit" class = "btn btn-danger more"> Ara</button>
                                </form>
                            </div>
                        
                    </div>
                </div>
            </section>
            
            
{% endblock Title %}



{% block content %}

            <section id = "translateArticlesList">
                {% if karisikArticles %}
                {% for articlecontext in  karisikArticles %}
                <div class = "container">
                    <div class = "translateArticles-content text-center">
                        <div class = "row">
                            <div class = "col-lg-6 distance article">
                                {% if articlecontext.articleImage %}
                                <div class ="text-center distance">
                                    <img class = "image" style="max-width:100%; margin: 2%;" src = "{{articlecontext.articleImage.url}}" alt = ""/>
                                </div>
                                {% endif %}
                            </div>
                            <div class = "col-lg-6 text-left distance article">
                                <h4> {{articlecontext.title | safe}}</h4> 
                                <p> {{articlecontext.content | safe | truncatechars_html:200}}</p>
                                <a style = "float : right;" href = "{% url 'articles:karisikDetail' articlecontext.id %}" class = "btn btn-danger more"> Devamını Oku</a>
                            </div>

                            <div class = "col-lg-12 distance middle">
                            </div>
                        </div>
                    </div>
                </div>
                {% endfor %}
                {% else %}
                <div class = "alert alert-danger">
                Henüz makale eklenmemiştir
                </div>
                {% endif %}   
            </section>



            <nav aria-label="Page navigation example" style = "background-color: #E0E0E0;">
                <ul class="pagination">
                    {% if karisikArticles.has_previous %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ karisikArticles.previous_page_number }}" aria-label="Previous">
                            <span aria-hidden="true">&laquo;</span>
                            <span class="sr-only">Previous</span>
                        </a>
                    </li>
                    {% endif %}

                    {% if karisikArticles.paginator.num_pages %}
                    <span class="current ">
                        Sayfa {{ karisikArticles.paginator.num_pages  | safe}} / {{ karisikArticles.number  | safe}}
                    </span>
                    {% endif %}

                    {% if karisikArticles.has_next %}
                    <li class="page-item">
                        <a class="page-link"  href="?page={{ karisikArticles.next_page_number }}" aria-label="Next">
                            <span aria-hidden="true">&raquo;</span>
                            <span class="sr-only">Next</span>
                        </a>
                    </li>
                    {% endif %}
                </ul>
            </nav>

{% endblock content %}